snap

diff --git a/bpfman-sqlite b/bpfman-sqlite
--- a/bpfman-sqlite
+++ b/bpfman-sqlite
@@ -43,6 +43,12 @@ set -o errexit
 set -o nounset
 set -o pipefail
 
+command -v sqlite3 >/dev/null || {
+    echo "Error: sqlite3 not found in PATH" >&2
+    exit 1
+}
+
+
 if [ $# -lt 1 ]; then
     echo "Usage: ${0##*/} /path/to/db.sqlite [ <SQLite-args>... ]" >&2
     exit 1
